### ISSUE TITLE
Could not load facroy with ES6

### ISSUE THREAD

**Issue by kiennt** [zand3rs/sails-factory#7]
I am using ES6 with sails  and sails-factory

Here `bootstrap.js`

``` js
/* eslint strict: [2, "global"] */

'use strict';

const Sails = require('sails');
const babel = require('sails-hook-babel/node_modules/babel/register');

const options = {
  loose: 'all',
  stage: 2,
  ignore: null,
  only: null,
  extensions: null,
};
global.babel = babel(options);

before(done => {
  Sails.lift({}, (err, sails) => {
    if (err) return done(err);
    require('sails-factory').load();
    done(err, sails);
  });
});

after(done => Sails.lower(done));
```

And here is error logs

```
$ npm test

> tcg-scheduler@0.0.0 test /Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler
> mocha test/bootstrap.js test/unit/**/*.test.js --timeout 60000



info: 
info:                .-..-.
info: 
info:    Sails              <|    .-..-.
info:    v0.11.2             |\
info:                       /|.\
info:                      / || \
info:                    ,'  |'  \
info:                 .-'.-==|/_--'
info:                 `--'-------' 
info:    __---___--___---___--___---___--___
info:  ____---___--___---___--___---___--___-__
info: 
info: Server lifted in `/Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler`
info: To see your app, visit http://localhost:1337
info: To shut down Sails, press <CTRL> + C at any time.

debug: --------------------------------------------------------
debug: :: Tue Oct 20 2015 15:32:21 GMT+0700 (ICT)

debug: Environment : development
debug: Port        : 1337
debug: --------------------------------------------------------
error: The bootstrap function threw an error after its callback was called :: TypeError: Cannot read property 'caller' of null
    at Function.Factory.define (/Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails-factory/index.js:69:39)
    at module.exports (/Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/test/factories/Job.js:2:11)
    at requireFactory (/Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails-factory/index.js:200:18)
    at /Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails-factory/index.js:189:18
    at Array.forEach (native)
    at requireAll (/Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails-factory/index.js:183:9)
    at Function.Factory.load (/Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails-factory/index.js:172:3)
    at /Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/test/bootstrap.js:20:30
    at sailsReady (/Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails/lib/app/lift.js:49:12)
    at /Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails/node_modules/async/lib/async.js:251:17
    at /Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails/node_modules/async/lib/async.js:154:25
    at /Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails/node_modules/async/lib/async.js:248:21
    at /Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails/node_modules/async/lib/async.js:612:34
    at afterBootstrap (/Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails/lib/app/private/initialize.js:57:5)
    at bootstrapDone (/Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails/lib/app/private/bootstrap.js:51:14)
    at Object.module.exports.bootstrap (/Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/config/bootstrap.js:7:3)
    at Sails.runBootstrap (/Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails/lib/app/private/bootstrap.js:44:25)
    at Sails.bound [as runBootstrap] (/Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at Sails.initialize (/Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails/lib/app/private/initialize.js:48:9)
    at bound (/Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at /Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails/node_modules/async/lib/async.js:607:21
    at /Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails/node_modules/async/lib/async.js:246:17
    at iterate (/Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails/node_modules/async/lib/async.js:146:13)
    at /Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails/node_modules/async/lib/async.js:157:25
    at /Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails/node_modules/async/lib/async.js:248:21
    at /Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails/node_modules/async/lib/async.js:612:34
    at /Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails/lib/app/load.js:201:13
    at /Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails/node_modules/async/lib/async.js:451:17
    at /Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails/node_modules/async/lib/async.js:441:17
    at _each (/Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails/node_modules/async/lib/async.js:46:13)
    at Immediate.taskComplete (/Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails/node_modules/async/lib/async.js:440:13)
    at processImmediate [as _immediateCallback] (timers.js:368:17) [TypeError: Cannot read property 'caller' of null]
```

**Comment by zand3rs** [comment]
Please let me see also what's in this file:

/Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/test/factories/Job.js

**Comment by kiennt** [comment]
Here is my Job.js files

``` js
import moment from 'moment';

module.exports = {
  autoCreatedAt: false,
  autoUpdatedAt: false,
  attributes: {
    id: { type: 'string', required: true, primaryKey: true },
    startAt: { type: 'datetime', required: true, columnName: 'start_at' },
    checkSum: { type: 'string', required: true, columnName: 'check_sum' },
    isFinished: { type: 'boolean', defaultsTo: false, columnName: 'is_finished' },

    toJSON: function() {
      const obj = this.toObject();
      obj.startAt = moment(obj.startAt).from(moment(new Date()));
      return obj;
    },
  },
};
```

And here is `factory/Job.js`

``` js
module.exports = (factory) => {
  factory.define('job')
    .attr('id', 0, { auto_increment: true })
    .attr('startAt', Date.new())
    .attr('isFinished', false);
};
```

**Comment by zand3rs** [comment]
Hi @kiennt,

Your factory/Job.js will definitely not work as expected due to the nature of the arrow function. The factory loader highly depends on the function arguments variable which the arrow function doesn't have. You can refer to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions for more info.

Please use the default function expression instead.

**Comment by zand3rs** [comment]
closing this issue for now

**Comment by kiennt** [comment]
@zand3rs After coverting arrow function to normal function, it still does not work

``` js
// test/bootstrap.js
/* eslint strict: [2, "global"] */

const Sails = require('sails');
const babel = require('sails-hook-babel/node_modules/babel/register');
const factory = require('sails-factory');

const options = {
  loose: 'all',
  stage: 2,
  ignore: null,
  only: null,
  extensions: null,
};
global.babel = babel(options);

before(function(done) {
  Sails.lift({}, function(err, sails) {
    if (err) return done(err);
    factory.load();
    done(err, sails);
  });
});

after(function(done) {
  Sails.lower(done);
});
```

``` js

// factories/Job.js

module.exports = function(factory) {
  factory.define('job')
    .attr('id', 0, { auto_increment: true })
    .attr('startAt', Date.new())
    .attr('isFinished', false);
};

```

**Comment by zand3rs** [comment]
what's the error?

**Comment by kiennt** [comment]
The same error as I described before

``` bash
$ npm test

> tcg-scheduler@0.0.0 test /Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler
> mocha test/bootstrap.js test/unit/**/*.test.js --timeout 60000



info: 
info:                .-..-.
info: 
info:    Sails              <|    .-..-.
info:    v0.11.2             |\
info:                       /|.\
info:                      / || \
info:                    ,'  |'  \
info:                 .-'.-==|/_--'
info:                 `--'-------' 
info:    __---___--___---___--___---___--___
info:  ____---___--___---___--___---___--___-__
info: 
info: Server lifted in `/Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler`
info: To see your app, visit http://localhost:1337
info: To shut down Sails, press <CTRL> + C at any time.

debug: --------------------------------------------------------
debug: :: Tue Oct 20 2015 15:32:21 GMT+0700 (ICT)

debug: Environment : development
debug: Port        : 1337
debug: --------------------------------------------------------
error: The bootstrap function threw an error after its callback was called :: TypeError: Cannot read property 'caller' of null
    at Function.Factory.define (/Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails-factory/index.js:69:39)
    at module.exports (/Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/test/factories/Job.js:2:11)
    at requireFactory (/Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails-factory/index.js:200:18)
    at /Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails-factory/index.js:189:18
    at Array.forEach (native)
    at requireAll (/Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails-factory/index.js:183:9)
    at Function.Factory.load (/Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails-factory/index.js:172:3)
    at /Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/test/bootstrap.js:20:30
    at sailsReady (/Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails/lib/app/lift.js:49:12)
    at /Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails/node_modules/async/lib/async.js:251:17
    at /Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails/node_modules/async/lib/async.js:154:25
    at /Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails/node_modules/async/lib/async.js:248:21
    at /Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails/node_modules/async/lib/async.js:612:34
    at afterBootstrap (/Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails/lib/app/private/initialize.js:57:5)
    at bootstrapDone (/Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails/lib/app/private/bootstrap.js:51:14)
    at Object.module.exports.bootstrap (/Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/config/bootstrap.js:7:3)
    at Sails.runBootstrap (/Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails/lib/app/private/bootstrap.js:44:25)
    at Sails.bound [as runBootstrap] (/Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at Sails.initialize (/Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails/lib/app/private/initialize.js:48:9)
    at bound (/Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at /Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails/node_modules/async/lib/async.js:607:21
    at /Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails/node_modules/async/lib/async.js:246:17
    at iterate (/Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails/node_modules/async/lib/async.js:146:13)
    at /Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails/node_modules/async/lib/async.js:157:25
    at /Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails/node_modules/async/lib/async.js:248:21
    at /Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails/node_modules/async/lib/async.js:612:34
    at /Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails/lib/app/load.js:201:13
    at /Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails/node_modules/async/lib/async.js:451:17
    at /Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails/node_modules/async/lib/async.js:441:17
    at _each (/Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails/node_modules/async/lib/async.js:46:13)
    at Immediate.taskComplete (/Volumes/DATA/TRUSTCIRCLE/BACKEND/backend-scheduler/node_modules/sails/node_modules/async/lib/async.js:440:13)
    at processImmediate [as _immediateCallback] (timers.js:368:17) [TypeError: Cannot read property 'caller' of null]
```

**Comment by zand3rs** [comment]
Hi @kiennt,

I tried your code and it is failing on your factory definition:

```
// factories/Job.js
module.exports = function(factory) {
  factory.define('job')
    .attr('id', 0, { auto_increment: true })
    .attr('startAt', Date.new())
    .attr('isFinished', false);
};
```

I'm not sure how you came up with **Date.new()** but after changing it to **new Date()** it worked perfectly.

**Comment by kiennt** [comment]
@zand3rs oh, it 's my bad.

But I cached it back to `new Date()` and run again.

But it still has error as above. 

I am wonder is that because other class I am using ES6 for other classes?
